"""Initial schema

Revision ID: 5569b9055e40
Revises: 
Create Date: 2026-01-31 22:57:12.438696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5569b9055e40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_number', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('personality_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("model_type IN ('claude-sonnet-4', 'gpt-4o-mini', 'claude-haiku', 'llama-3.3-70b', 'llama-3.1-8b', 'gemini-flash')", name='valid_model'),
    sa.CheckConstraint("personality_type IN ('efficiency', 'equality', 'freedom', 'stability', 'neutral')", name='valid_personality'),
    sa.CheckConstraint("status IN ('active', 'dormant')", name='valid_status'),
    sa.CheckConstraint('agent_number >= 1 AND agent_number <= 100', name='valid_agent_number'),
    sa.CheckConstraint('tier >= 1 AND tier <= 4', name='valid_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_number')
    )
    op.create_table('global_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('in_common_pool', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('produced_today', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('consumed_today', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("resource_type IN ('food', 'energy', 'materials', 'land')", name='valid_resource_type'),
    sa.CheckConstraint('quantity >= 0', name='non_negative_quantity'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_cost', sa.JSON(), nullable=False),
    sa.Column('built_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('maintained_by', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('efficiency_bonus', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('proposed', 'building', 'active', 'defunct')", name='valid_infra_status'),
    sa.ForeignKeyConstraint(['built_by_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_agent_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('recipient_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("message_type IN ('forum_post', 'forum_reply', 'direct_message', 'system_alert')", name='valid_message_type'),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['recipient_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('proposal_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('votes_for', sa.Integer(), nullable=False),
    sa.Column('votes_against', sa.Integer(), nullable=False),
    sa.Column('votes_abstain', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('voting_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("proposal_type IN ('law', 'allocation', 'rule', 'infrastructure', 'constitutional', 'other')", name='valid_proposal_type'),
    sa.CheckConstraint("status IN ('active', 'passed', 'failed', 'expired')", name='valid_proposal_status'),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_agent_id', sa.Integer(), nullable=True),
    sa.Column('to_agent_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("resource_type IN ('food', 'energy', 'materials', 'land')", name='valid_tx_resource'),
    sa.CheckConstraint("transaction_type IN ('work_production', 'trade', 'allocation', 'consumption', 'building', 'awakening', 'initial_distribution')", name='valid_tx_type'),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author_agent_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('passed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('repealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repealed_by_proposal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['repealed_by_proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("vote IN ('yes', 'no', 'abstain')", name='valid_vote'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('laws')
    op.drop_table('transactions')
    op.drop_table('proposals')
    op.drop_table('messages')
    op.drop_table('infrastructure')
    op.drop_table('events')
    op.drop_table('agent_inventory')
    op.drop_table('agent_actions')
    op.drop_table('global_resources')
    op.drop_table('agents')
    # ### end Alembic commands ###
